import { type SkillDocInput, type SkillFile, SkillFileSchema } from '@skillgraph/core';

export interface Template {
  id: string;
  name: string;
  description: string;
  build: (name: string) => SkillFile;
}

function file(doc: SkillDocInput): SkillFile {
  return SkillFileSchema.parse({
    schemaVersion: 1,
    doc,
    layout: { nodes: {}, viewport: { x: 0, y: 0, zoom: 1 } },
  });
}

export const TEMPLATES: Template[] = [
  {
    id: 'blank',
    name: 'Blank',
    description: 'Just the skill entry. Add nodes from the palette.',
    build: (name) =>
      file({
        nodes: [
          {
            id: 'entry_root',
            kind: 'entry',
            name,
            title: humanize(name),
            description: `${humanize(name)}. Use when …`,
            order: 0,
          },
        ],
        edges: [],
      }),
  },
  {
    id: 'workflow',
    name: 'Workflow',
    description:
      'Phases with numbered steps, a decision, an output template and a verification checklist.',
    build: (name) =>
      file({
        nodes: [
          {
            id: 'entry_root',
            kind: 'entry',
            name,
            title: humanize(name),
            summary: `${humanize(name)} in three phases.`,
            description: `${humanize(name)}. Use whenever the user asks for … even if they do not say "${name}" explicitly.`,
            overview: 'auto',
            order: 0,
          },
          {
            id: 'phase_understand',
            kind: 'phase',
            title: 'Understand',
            summary: 'Gather what the task needs.',
            order: 1,
          },
          {
            id: 'step_restate',
            kind: 'step',
            parentId: 'phase_understand',
            order: 1,
            title: 'Restate the request',
            instruction: 'in one sentence and confirm the goal.',
            why: 'A wrong goal wastes every later step.',
          },
          {
            id: 'ask_gaps',
            kind: 'ask_user',
            parentId: 'phase_understand',
            order: 2,
            title: 'Fill the gaps',
            question: 'Ask for anything missing (inputs, constraints, definition of done).',
            blocking: true,
          },
          {
            id: 'phase_do',
            kind: 'phase',
            title: 'Do the work',
            summary: 'Pick the path that fits the input.',
            order: 2,
          },
          {
            id: 'dec_kind',
            kind: 'decision',
            parentId: 'phase_do',
            order: 1,
            question: 'What kind of input did the user give?',
          },
          {
            id: 'step_files',
            kind: 'step',
            parentId: 'phase_do',
            order: 2,
            title: 'Read the files',
            instruction: 'and apply the rules below.',
          },
          {
            id: 'step_nothing',
            kind: 'step',
            parentId: 'phase_do',
            order: 3,
            title: 'Ask which files',
            instruction: 'to work on before doing anything else.',
          },
          {
            id: 'step_apply',
            kind: 'step',
            parentId: 'phase_do',
            order: 4,
            title: 'Apply the change',
            instruction: 'in small, reviewable increments.',
          },
          {
            id: 'phase_ship',
            kind: 'phase',
            title: 'Ship',
            summary: 'Produce the deliverable and verify it.',
            order: 3,
          },
          {
            id: 'step_report',
            kind: 'step',
            parentId: 'phase_ship',
            order: 1,
            title: 'Write the report',
            instruction: 'using the output template.',
          },
          {
            id: 'ref_rules',
            kind: 'reference',
            path: 'references/rules.md',
            body: '# Rules\n\n- Prefer the simplest change that works.\n',
            summary: 'the detailed rules',
            readWhen: 'you are unsure whether a change is allowed',
            order: 900,
          },
          {
            id: 'out_report',
            kind: 'output_format',
            template: '## Summary\n\n## Changes\n\n## Open questions',
            format: 'markdown',
            strictness: 'exact',
            order: 10,
          },
          {
            id: 'guard_1',
            kind: 'guardrail',
            polarity: 'dont',
            text: "Don't guess at requirements.",
            why: 'A clarifying question is cheaper than a wrong deliverable.',
            order: 11,
          },
          {
            id: 'check_1',
            kind: 'checklist',
            variant: 'verification',
            items: [
              { text: 'The report follows the template.' },
              { text: 'Every change was explained.' },
            ],
            order: 12,
          },
        ],
        edges: [
          { id: 'e1', kind: 'next', source: 'step_restate', target: 'ask_gaps' },
          {
            id: 'e2',
            kind: 'branch',
            source: 'dec_kind',
            target: 'step_files',
            label: 'Files or a pattern?',
          },
          {
            id: 'e3',
            kind: 'branch',
            source: 'dec_kind',
            target: 'step_nothing',
            label: 'Nothing?',
          },
          { id: 'e4', kind: 'next', source: 'step_files', target: 'step_apply' },
          { id: 'e5', kind: 'next', source: 'step_nothing', target: 'step_apply' },
          { id: 'e6', kind: 'reads', source: 'step_apply', target: 'ref_rules' },
        ],
      }),
  },
  {
    id: 'knowledge',
    name: 'Knowledge router',
    description: 'A priority table of categories that routes to small reference files.',
    build: (name) =>
      file({
        nodes: [
          {
            id: 'entry_root',
            kind: 'entry',
            name,
            title: humanize(name),
            summary: 'Best practices organized by category and prioritized by impact.',
            description: `${humanize(name)} best practices. Use when writing, reviewing or refactoring code in this area.`,
            referenceIndex: 'none',
            order: 0,
          },
          { id: 'phase_when', kind: 'phase', title: 'When to Apply', order: 1 },
          {
            id: 'raw_when',
            kind: 'raw_markdown',
            parentId: 'phase_when',
            order: 1,
            body: 'Reference these guidelines when:\n\n- Writing new code\n- Reviewing changes\n',
          },
          {
            id: 'catalog_1',
            kind: 'catalog',
            title: 'Rule Categories by Priority',
            quickReference: 'auto',
            categories: [
              { id: 'perf', name: 'Performance', impact: 'CRITICAL', prefix: 'perf-' },
              { id: 'safety', name: 'Safety', impact: 'HIGH', prefix: 'safety-' },
            ],
            order: 2,
          },
          {
            id: 'ref_a',
            kind: 'reference',
            path: 'references/perf-avoid-waterfalls.md',
            body: '# Avoid waterfalls\n\nStart independent work in parallel.\n',
            summary: 'Start independent work in parallel',
            categoryId: 'perf',
            order: 900,
          },
          {
            id: 'ref_b',
            kind: 'reference',
            path: 'references/safety-validate-input.md',
            body: '# Validate input\n\nNever trust external data.\n',
            summary: 'Never trust external data',
            categoryId: 'safety',
            order: 901,
          },
        ],
        edges: [],
      }),
  },
  {
    id: 'stub',
    name: 'Stub (fetch the real rules)',
    description: 'A tiny skill that fetches a URL and applies what it finds.',
    build: (name) =>
      file({
        nodes: [
          {
            id: 'entry_root',
            kind: 'entry',
            name,
            title: humanize(name),
            description: `Review files against ${humanize(name)}. Use when asked to review UI, check accessibility or audit a design.`,
            claudeCode: { argumentHint: '<file-or-pattern>' },
            order: 0,
          },
          { id: 'phase_how', kind: 'phase', title: 'How It Works', order: 1 },
          {
            id: 'step_fetch',
            kind: 'step',
            parentId: 'phase_how',
            order: 1,
            title: 'Fetch the latest guidelines',
            instruction: 'before each review.',
          },
          {
            id: 'step_read',
            kind: 'step',
            parentId: 'phase_how',
            order: 2,
            title: 'Read the specified files',
            instruction: 'or ask the user for files or a pattern.',
          },
          {
            id: 'step_apply',
            kind: 'step',
            parentId: 'phase_how',
            order: 3,
            title: 'Apply every rule',
            instruction: 'and report findings as `file:line` lines.',
          },
          {
            id: 'ref_url',
            kind: 'reference',
            path: 'references/guidelines.md',
            source: 'url',
            url: 'https://example.com/guidelines.md',
            summary: 'all the rules and the output format',
            readWhen: 'before each review',
            order: 900,
          },
        ],
        edges: [
          { id: 'e1', kind: 'reads', source: 'step_fetch', target: 'ref_url' },
          { id: 'e2', kind: 'next', source: 'step_fetch', target: 'step_read' },
          { id: 'e3', kind: 'next', source: 'step_read', target: 'step_apply' },
        ],
      }),
  },
  {
    id: 'knowledge-router',
    name: 'Knowledge router (with decision)',
    description:
      'A decision that routes to three reference files, each with a read-when, plus a priority catalog.',
    build: (name) =>
      file({
        nodes: [
          {
            id: 'entry_root',
            kind: 'entry',
            name,
            title: humanize(name),
            summary: `${humanize(name)} rules, split into small reference files so only the relevant ones are loaded.`,
            description: `${humanize(name)} guidance organized by topic and prioritized by impact. Use whenever the user writes, reviews or debugs code in this area, even if they do not ask for best practices explicitly.`,
            referenceIndex: 'none',
            order: 0,
          },
          {
            id: 'phase_route',
            kind: 'phase',
            title: 'How to use',
            summary: 'Load only the rules that match the task.',
            order: 1,
          },
          {
            id: 'dec_topic',
            kind: 'decision',
            parentId: 'phase_route',
            order: 1,
            question: 'What is the user working on?',
            intro: 'Pick the reference that matches the task, then apply every rule in it.',
          },
          {
            id: 'step_perf',
            kind: 'step',
            parentId: 'phase_route',
            order: 2,
            title: 'Performance',
            instruction: 'concerns: slow pages, request waterfalls, bundle size.',
          },
          {
            id: 'step_security',
            kind: 'step',
            parentId: 'phase_route',
            order: 3,
            title: 'Security',
            instruction: 'concerns: untrusted input, secrets, access control.',
          },
          {
            id: 'step_style',
            kind: 'step',
            parentId: 'phase_route',
            order: 4,
            title: 'Structure and style',
            instruction: 'concerns: naming, module boundaries, readability.',
          },
          {
            id: 'step_cite',
            kind: 'step',
            parentId: 'phase_route',
            order: 5,
            title: 'Cite the rule',
            instruction: 'by its id (for example `perf-1`) next to every finding or change.',
            why: 'A named rule lets the user look it up and push back on a specific point.',
          },
          {
            id: 'catalog_rules',
            kind: 'catalog',
            title: 'Rule categories by priority',
            intro: 'Higher rows matter more; fix a critical finding before a medium one.',
            quickReference: 'auto',
            categories: [
              {
                id: 'perf',
                name: 'Performance',
                impact: 'CRITICAL',
                prefix: 'perf-',
                description: 'Eliminate waterfalls and oversized bundles',
              },
              {
                id: 'security',
                name: 'Security',
                impact: 'HIGH',
                prefix: 'sec-',
                description: 'Validate input and protect secrets',
              },
              {
                id: 'style',
                name: 'Structure and style',
                impact: 'MEDIUM',
                prefix: 'style-',
                description: 'Keep modules small and names honest',
              },
            ],
            order: 2,
          },
          {
            id: 'ref_perf',
            kind: 'reference',
            path: 'references/perf-rendering.md',
            body: '# Performance rules\n\n## perf-1: Start independent requests together\n\nAwait `Promise.all` over independent fetches instead of chaining them.\n\n## perf-2: Import heavy modules lazily\n\nUse dynamic `import()` for code that only some users reach.\n',
            summary: 'the performance rules (waterfalls, lazy loading)',
            readWhen: 'the task touches data fetching, rendering or bundle size',
            categoryId: 'perf',
            order: 900,
          },
          {
            id: 'ref_security',
            kind: 'reference',
            path: 'references/sec-input.md',
            body: '# Security rules\n\n## sec-1: Validate at the boundary\n\nParse every external payload with a schema before using it.\n\n## sec-2: Keep secrets out of the client\n\nRead API keys on the server only; never ship them in a bundle.\n',
            summary: 'the security rules (input validation, secrets)',
            readWhen: 'the task handles user input, authentication or credentials',
            categoryId: 'security',
            order: 901,
          },
          {
            id: 'ref_style',
            kind: 'reference',
            path: 'references/style-structure.md',
            body: '# Structure and style rules\n\n## style-1: One reason to change per module\n\nSplit a file when it serves two unrelated callers.\n\n## style-2: Name by intent, not by type\n\n`retryDelayMs` beats `number1`.\n',
            summary: 'the structure and naming rules',
            readWhen: 'the task is a refactor or a review of readability',
            categoryId: 'style',
            order: 902,
          },
        ],
        edges: [
          { id: 'e1', kind: 'branch', source: 'dec_topic', target: 'step_perf', label: 'Speed?' },
          {
            id: 'e2',
            kind: 'branch',
            source: 'dec_topic',
            target: 'step_security',
            label: 'Safety?',
          },
          {
            id: 'e3',
            kind: 'branch',
            source: 'dec_topic',
            target: 'step_style',
            label: 'Readability?',
          },
          { id: 'e4', kind: 'reads', source: 'step_perf', target: 'ref_perf' },
          { id: 'e5', kind: 'reads', source: 'step_security', target: 'ref_security' },
          { id: 'e6', kind: 'reads', source: 'step_style', target: 'ref_style' },
          { id: 'e7', kind: 'next', source: 'step_perf', target: 'step_cite' },
          { id: 'e8', kind: 'next', source: 'step_security', target: 'step_cite' },
          { id: 'e9', kind: 'next', source: 'step_style', target: 'step_cite' },
        ],
      }),
  },
  {
    id: 'tool-wrapper',
    name: 'Tool wrapper',
    description:
      'A bundled script with a usage block, steps that run it and interpret the output, pre-approved via allowed-tools.',
    build: (name) =>
      file({
        nodes: [
          {
            id: 'entry_root',
            kind: 'entry',
            name,
            title: humanize(name),
            summary: `Wraps the bundled \`${name}\` check script so its output is read the same way every time.`,
            description: `Runs the bundled ${humanize(name)} check on a path and turns the raw output into a short report. Use whenever the user asks to check, audit or validate a folder with ${humanize(name)}, even if they only paste a path.`,
            autoAllowScripts: true,
            claudeCode: { argumentHint: '<path>' },
            order: 0,
          },
          {
            id: 'phase_run',
            kind: 'phase',
            title: 'Workflow',
            summary: 'Run the script, read its JSON, report.',
            order: 1,
          },
          {
            id: 'step_run',
            kind: 'step',
            parentId: 'phase_run',
            order: 1,
            title: 'Run the check',
            instruction: 'on the path the user gave (default: the current directory).',
            why: 'The script is deterministic; reasoning about the files by hand is slower and misses cases.',
          },
          {
            id: 'step_interpret',
            kind: 'step',
            parentId: 'phase_run',
            order: 2,
            title: 'Interpret the JSON',
            instruction:
              'output: `ok` is the overall verdict, `findings[]` lists `{ path, line, rule, message }`. Group findings by `rule` and count them.',
          },
          {
            id: 'step_report',
            kind: 'step',
            parentId: 'phase_run',
            order: 3,
            title: 'Report',
            instruction:
              'using the output template. Quote each finding as `path:line` so the user can jump to it.',
          },
          {
            id: 'script_check',
            kind: 'script',
            path: 'scripts/check.sh',
            language: 'bash',
            args: ['<path>', '--json'],
            runWhen: 'produce the raw findings',
            outputs: 'JSON on stdout: { ok, findings: [{ path, line, rule, message }] }',
            usage: 'bash scripts/check.sh <path> --json',
            // biome-ignore lint/suspicious/noTemplateCurlyInString: shell parameter expansion, not a JS template
            code: '#!/usr/bin/env bash\n# Check a folder and print findings as JSON.\nset -euo pipefail\n\nTARGET="${1:-.}"\nFORMAT="${2:---text}"\n\nfindings=()\nwhile IFS= read -r -d \'\' f; do\n  if grep -n "TODO" "$f" >/dev/null 2>&1; then\n    line=$(grep -n "TODO" "$f" | head -1 | cut -d: -f1)\n    findings+=("{\\"path\\":\\"$f\\",\\"line\\":$line,\\"rule\\":\\"no-todo\\",\\"message\\":\\"Unresolved TODO\\"}")\n  fi\ndone < <(find "$TARGET" -type f -name \'*.md\' -print0)\n\nif [ "$FORMAT" = "--json" ]; then\n  ok=true; [ ${#findings[@]} -gt 0 ] && ok=false\n  printf \'{"ok":%s,"findings":[%s]}\\n\' "$ok" "$(IFS=,; echo "${findings[*]}")"\nelse\n  printf \'%s\\n\' "${findings[@]}"\nfi\n',
            order: 900,
          },
          {
            id: 'out_report',
            kind: 'output_format',
            template:
              '## Check: <path>\n\n**Verdict:** pass | fail (N findings)\n\n| Rule | Count |\n|---|---|\n| no-todo | 3 |\n\n### Findings\n\n- `path:line` - message',
            format: 'markdown',
            strictness: 'guide',
            order: 10,
          },
          {
            id: 'guard_no_edit',
            kind: 'guardrail',
            polarity: 'dont',
            text: "Don't paraphrase or 'fix' the script output before reporting it.",
            why: 'The user relies on the report matching what the tool actually found.',
            order: 11,
          },
          {
            id: 'guard_missing',
            kind: 'guardrail',
            polarity: 'do',
            text: 'Do report a non-zero exit code as a failed run, not as "no findings".',
            why: 'A crashed check that looks clean is worse than no check.',
            order: 12,
          },
        ],
        edges: [
          { id: 'e1', kind: 'runs', source: 'step_run', target: 'script_check' },
          { id: 'e2', kind: 'next', source: 'step_run', target: 'step_interpret' },
          { id: 'e3', kind: 'next', source: 'step_interpret', target: 'step_report' },
        ],
      }),
  },
  {
    id: 'reviewer',
    name: 'Reviewer',
    description:
      'Gather, review, report: a verification checklist, guardrails and a strict output template.',
    build: (name) =>
      file({
        nodes: [
          {
            id: 'entry_root',
            kind: 'entry',
            name,
            title: humanize(name),
            summary:
              'Reviews a change against a fixed checklist and reports findings in a consistent shape.',
            description: `Reviews code changes for correctness, safety and clarity using the ${humanize(name)} checklist. Use whenever the user asks for a review, feedback, a second opinion or a pre-merge check on a diff, PR or file, even if they only paste a snippet.`,
            overview: 'auto',
            order: 0,
          },
          {
            id: 'phase_gather',
            kind: 'phase',
            title: 'Gather context',
            summary: 'Know what changed and why before judging it.',
            order: 1,
          },
          {
            id: 'step_scope',
            kind: 'step',
            parentId: 'phase_gather',
            order: 1,
            title: 'Identify the change',
            instruction:
              'to review: a diff, a PR number, a file or a pasted snippet. Read all of it before commenting.',
            why: 'Partial reading produces confident comments about code that was already handled elsewhere.',
          },
          {
            id: 'step_intent',
            kind: 'step',
            parentId: 'phase_gather',
            order: 2,
            title: 'State the intent',
            instruction: 'of the change in one sentence; ask if it is unclear.',
          },
          {
            id: 'phase_review',
            kind: 'phase',
            title: 'Review',
            summary: 'Correctness first, then safety, then clarity.',
            order: 2,
          },
          {
            id: 'step_correct',
            kind: 'step',
            parentId: 'phase_review',
            order: 1,
            title: 'Check correctness',
            instruction:
              ': does the code do what the intent says for the normal path, the empty path and the failure path?',
          },
          {
            id: 'step_safety',
            kind: 'step',
            parentId: 'phase_review',
            order: 2,
            title: 'Check safety',
            instruction:
              ': untrusted input, secrets, destructive operations, missing error handling.',
          },
          {
            id: 'step_clarity',
            kind: 'step',
            parentId: 'phase_review',
            order: 3,
            title: 'Check clarity',
            instruction: ': naming, dead code, duplicated logic, tests that prove the change.',
          },
          {
            id: 'phase_report',
            kind: 'phase',
            title: 'Report',
            summary: 'Findings the author can act on.',
            order: 3,
          },
          {
            id: 'step_rank',
            kind: 'step',
            parentId: 'phase_report',
            order: 1,
            title: 'Rank findings',
            instruction: 'as blocker, should-fix or nit, and drop anything you cannot justify.',
          },
          {
            id: 'step_write',
            kind: 'step',
            parentId: 'phase_report',
            order: 2,
            title: 'Write the review',
            instruction: 'using the output template, one finding per bullet with `file:line`.',
          },
          {
            id: 'out_review',
            kind: 'output_format',
            template:
              '## Review: <change>\n\n**Verdict:** approve | request changes\n\n### Blockers\n\n- `file:line` - what is wrong and why it matters\n\n### Should fix\n\n- `file:line` - ...\n\n### Nits\n\n- `file:line` - ...\n\n### What is good\n\n- one or two specific things worth keeping',
            format: 'markdown',
            strictness: 'exact',
            order: 10,
          },
          {
            id: 'guard_nits',
            kind: 'guardrail',
            polarity: 'dont',
            text: "Don't lead with style nits when a correctness problem exists.",
            why: 'Authors fix the first thing they read; make it the thing that matters.',
            order: 11,
          },
          {
            id: 'guard_rewrite',
            kind: 'guardrail',
            polarity: 'dont',
            text: "Don't rewrite the change yourself unless asked.",
            why: 'A review is feedback; unrequested rewrites hide what was wrong and why.',
            order: 12,
          },
          {
            id: 'guard_evidence',
            kind: 'guardrail',
            polarity: 'do',
            text: 'Do quote the exact line for every finding.',
            why: 'A finding without a location is a hunch, not a review.',
            order: 13,
          },
          {
            id: 'check_verify',
            kind: 'checklist',
            variant: 'verification',
            items: [
              {
                text: 'Every finding names a file and line.',
                why: 'The author must be able to jump straight to it.',
              },
              {
                text: 'Blockers are truly blocking (wrong output, data loss, security).',
              },
              { text: 'The verdict matches the findings.' },
              { text: 'At least one thing that is good was named.' },
            ],
            order: 14,
          },
          {
            id: 'example_review',
            kind: 'example',
            label: 'A finding',
            input: 'A handler that catches an error and returns `null` without logging.',
            output:
              '- `api/users.ts:42` - the catch swallows the error and returns `null`; callers treat `null` as "no user" and the outage is invisible. Log and rethrow, or return a typed error.',
            order: 15,
          },
        ],
        edges: [
          { id: 'e1', kind: 'next', source: 'step_scope', target: 'step_intent' },
          { id: 'e2', kind: 'next', source: 'step_correct', target: 'step_safety' },
          { id: 'e3', kind: 'next', source: 'step_safety', target: 'step_clarity' },
          { id: 'e4', kind: 'next', source: 'step_rank', target: 'step_write' },
        ],
      }),
  },
  {
    id: 'interview',
    name: 'Interview',
    description:
      'One question at a time: ask_user nodes with options and a loop that ends when the goal is clear.',
    build: (name) =>
      file({
        nodes: [
          {
            id: 'entry_root',
            kind: 'entry',
            name,
            title: humanize(name),
            summary:
              'Turns a vague request into a one-paragraph brief by asking one question at a time.',
            description: `Interviews the user one question at a time until the goal, audience and definition of done are clear, then writes a brief. Use whenever a request is underspecified ("build me X" with no who or why), even if the user has not asked to be interviewed.`,
            order: 0,
          },
          {
            id: 'phase_interview',
            kind: 'phase',
            title: 'Interview',
            summary: 'Short questions, one at a time, with options where possible.',
            order: 1,
          },
          {
            id: 'ask_scope',
            kind: 'ask_user',
            parentId: 'phase_interview',
            order: 1,
            title: 'Start with the outcome',
            question: 'What should be true when this is done?',
            options: [
              'A working feature someone can use',
              'A decision or recommendation',
              'A document or plan',
              'Something else (describe it)',
            ],
            blocking: true,
            why: 'The outcome decides which follow-up questions are worth asking.',
          },
          {
            id: 'loop_probe',
            kind: 'loop',
            parentId: 'phase_interview',
            order: 2,
            title: 'Probe',
            until:
              'you can state the goal, the audience and the definition of done in one paragraph and the user agrees',
            maxIterations: 8,
            intro: 'Ask about the biggest remaining unknown, never two things at once.',
          },
          {
            id: 'ask_next',
            kind: 'ask_user',
            parentId: 'loop_probe',
            order: 1,
            title: 'Ask the next question',
            question:
              'Pick the unknown that would most change the plan (who is it for, what exists today, what is out of scope, how will success be judged) and ask about it.',
            options: ['Offer 2-4 concrete options', 'Include "not sure" as an option'],
            blocking: true,
          },
          {
            id: 'step_reflect',
            kind: 'step',
            parentId: 'loop_probe',
            order: 2,
            title: 'Reflect the answer',
            instruction:
              'back in one sentence and update your running summary of goal, audience and definition of done.',
            why: 'Reflecting catches misunderstandings while they are still cheap to fix.',
          },
          {
            id: 'ask_confirm',
            kind: 'ask_user',
            parentId: 'phase_interview',
            order: 3,
            title: 'Confirm the brief',
            question: 'Read the one-paragraph brief back and ask whether it is right.',
            options: ['Yes, proceed', 'Almost, one correction', 'No, start over'],
            blocking: true,
          },
          {
            id: 'phase_brief',
            kind: 'phase',
            title: 'Write the brief',
            summary: 'The deliverable of the interview.',
            order: 2,
          },
          {
            id: 'step_brief',
            kind: 'step',
            parentId: 'phase_brief',
            order: 1,
            title: 'Write the brief',
            instruction: 'using the output template, then stop and hand it back to the user.',
          },
          {
            id: 'out_brief',
            kind: 'output_format',
            template:
              '## Brief\n\n**Goal:** one sentence\n\n**For:** who uses or reads the result\n\n**Done when:** observable criteria\n\n**Out of scope:** what we agreed not to do\n\n**Open questions:** anything still unknown',
            format: 'markdown',
            strictness: 'exact',
            order: 10,
          },
          {
            id: 'guard_one',
            kind: 'guardrail',
            polarity: 'dont',
            text: "Don't ask more than one question per turn.",
            why: 'Multi-part questions get partial answers and hide which part was unclear.',
            order: 11,
          },
          {
            id: 'guard_build',
            kind: 'guardrail',
            polarity: 'dont',
            text: "Don't start building before the brief is confirmed.",
            why: 'The interview exists to avoid building the wrong thing.',
            order: 12,
          },
        ],
        edges: [
          { id: 'e1', kind: 'next', source: 'ask_scope', target: 'loop_probe' },
          { id: 'e2', kind: 'next', source: 'ask_next', target: 'step_reflect' },
          { id: 'e3', kind: 'next', source: 'loop_probe', target: 'ask_confirm' },
        ],
      }),
  },
  {
    id: 'docs-first',
    name: 'Docs first',
    description: 'References that point at live URLs, fetched before answering, plus local notes.',
    build: (name) =>
      file({
        nodes: [
          {
            id: 'entry_root',
            kind: 'entry',
            name,
            title: humanize(name),
            summary: `Answers ${humanize(name)} questions from the official documentation instead of from memory.`,
            description: `Answers questions and writes code for ${humanize(name)} by fetching the official docs first. Use whenever the user asks how to do something with ${humanize(name)}, hits an error from it or wants an example, even if the answer seems obvious.`,
            order: 0,
          },
          {
            id: 'phase_answer',
            kind: 'phase',
            title: 'Workflow',
            summary: 'Fetch, then answer with citations.',
            order: 1,
          },
          {
            id: 'step_guide',
            kind: 'step',
            parentId: 'phase_answer',
            order: 1,
            title: 'Fetch the guide',
            instruction: 'for the topic the user asked about.',
            why: 'Training data lags releases; the guide is the source of truth for current behaviour.',
          },
          {
            id: 'step_api',
            kind: 'step',
            parentId: 'phase_answer',
            order: 2,
            title: 'Fetch the API reference',
            instruction: 'for every function or option you are about to name.',
          },
          {
            id: 'step_notes',
            kind: 'step',
            parentId: 'phase_answer',
            order: 3,
            title: 'Check the local notes',
            instruction: 'for known gotchas before writing the answer.',
          },
          {
            id: 'step_answer',
            kind: 'step',
            parentId: 'phase_answer',
            order: 4,
            title: 'Answer',
            instruction:
              'with a short explanation, a minimal example and a link to the exact doc section you used.',
          },
          {
            id: 'ref_guide',
            kind: 'reference',
            path: 'references/guide.md',
            source: 'url',
            url: 'https://example.com/docs/guide.md',
            summary: 'the concepts and recommended patterns',
            readWhen: 'before answering any how-to question',
            order: 900,
          },
          {
            id: 'ref_api',
            kind: 'reference',
            path: 'references/api.md',
            source: 'url',
            url: 'https://example.com/docs/api.md',
            summary: 'every function signature and option',
            readWhen: 'before naming a function, option or default value',
            order: 901,
          },
          {
            id: 'ref_notes',
            kind: 'reference',
            path: 'references/gotchas.md',
            body: '# Gotchas\n\n- The default timeout is shorter than most people expect; set it explicitly in examples.\n- Version 2 renamed `init()` to `create()`; check which major the user is on.\n',
            summary: 'gotchas the docs do not call out',
            readWhen: 'before finalizing an answer',
            order: 902,
          },
          {
            id: 'guard_memory',
            kind: 'guardrail',
            polarity: 'dont',
            text: "Don't answer from memory when the fetched docs disagree with it.",
            why: 'The docs describe the version the user has; memory describes an older one.',
            order: 11,
          },
          {
            id: 'guard_cite',
            kind: 'guardrail',
            polarity: 'do',
            text: 'Do link the exact section you relied on.',
            why: 'A link lets the user verify the claim and read further.',
            order: 12,
          },
        ],
        edges: [
          { id: 'e1', kind: 'reads', source: 'step_guide', target: 'ref_guide' },
          { id: 'e2', kind: 'reads', source: 'step_api', target: 'ref_api' },
          { id: 'e3', kind: 'reads', source: 'step_notes', target: 'ref_notes' },
          { id: 'e4', kind: 'next', source: 'step_guide', target: 'step_api' },
          { id: 'e5', kind: 'next', source: 'step_api', target: 'step_notes' },
          { id: 'e6', kind: 'next', source: 'step_notes', target: 'step_answer' },
        ],
      }),
  },
];

export function humanize(name: string): string {
  return name
    .split('-')
    .filter(Boolean)
    .map((w) => w[0]?.toUpperCase() + w.slice(1))
    .join(' ');
}
